### ISSUE TITLE
[Feature Request] Automatically save database when modified

### ISSUE THREAD

**Issue by miscreanttoucan** [mstarke/MacPass#287]
Can we please (pretty please?) have the option to auto-save the database after changing entries?

I can accomplish this in KeePass (Windows) by using the trigger system, but that's undoubtedly more work than needed at the moment.

My biggest concern is that I'll add or edit entries and then lose this information if I forget to save, the program crashes, etc.

**Comment by soliva** [comment]
+1

**Comment by gdovicak** [comment]
I was just burned bad by this. I had entered 5 or 6 passwords over the course of the past month and never saved. My mac just crashed. I rebooted and opened MacPass only to realize I never saved any of them.

For me, autosave would be a great feature, but I would be very happy with a more obvious notification that I have unsaved changes.

Because of my workflows I tend not to think of MacPass as a utility that reads and writes kdbx files, but more a password manager regardless of where they are saved. I don't utilize different password files across different machines like many others probably do so the fact that I have to save a file is not obvious to me.

**Comment by auge** [comment]
If we can have auto-save, I would propose (according to comment https://github.com/mstarke/MacPass/issues/287#issuecomment-68295328 ) to also enable auto-save on locking (this is also what can be set for KeePass).

**Comment by christophfroehlich** [comment]
+1

**Comment by mstarke** [comment]
@auge Autosave on locking is added in the current master.

**Comment by jeffmcneill** [comment]
Autosave on not locking and update-notify would be the magic combo for me. I've got at least two desktops (upstairs/downstairs) that could have a database open as well as a mobile device using Kypass. Autosave would really help and then for the other opened db getting a "database has updated / reload?" message, or even better simply auto-reloading. That way both systems will always be concurrent.

**Comment by mstarke** [comment]
@jeffmcneill autosafe on locking as well as modification notification is implemented and should work in 0.6.2 already.

**Comment by jinnko** [comment]
I'm using 0.6.2 (12420) and my laptop just crashed, losing a whole series of changes I made over a couple of hours :(

MacPass didn't lock within the time I was working.  Not sure exactly what "modification notification" refers to.

**Comment by jeffmcneill** [comment]
Hi @mstarke I still get conflicts with 0.6.2 and as far as I can tell there is no locking. Can this feature be better described so we can check to see if and when it is working?
![screen shot 2016-05-31 at 09 38 24](https://cloud.githubusercontent.com/assets/3119827/15661640/a8fa2c4a-2713-11e6-86d4-d626366e346a.png)

**Comment by mstarke** [comment]
Current master uses Autosave functionality from NSDocument so every change that is registered via the undo manager will trigger a save. All changes to entries and groups should therefor be stored immediately. There might be some kinks to work out. The .lock file is not monitored so MacPass *will* modify a file regardless!

**Comment by viktor-sc** [comment]
Hi,
is there a way to disable the autosave feature? I like to have the control about it...

Thanks,
Viktor

**Comment by mstarke** [comment]
A checkbox was added to disable autosave. 0.7.7 will include this. I think I need to add an advances preferences tab to make "low level" settings more obvious, since normal users might not fully grasp what consquences disabling autosave might have.

 
<img width="512" alt="Screenshot 2019-03-25 at 08 35 30" src="https://user-images.githubusercontent.com/58428/54902397-94090680-4ed9-11e9-9118-52082179285e.png">
