### ISSUE TITLE
Referenced passwords/usersnames don't work

### ISSUE THREAD

**Issue by frankhommers** [mstarke/MacPass#345]
If I copy an username/password in the original KeePass, and I duplicate the entry selecting "Replace user names and passwords by references" and I load that .kdbx into MacPass - it doesn't work correctly. I get a string containing {REF:U:I:xxxx} instead of the username and/or password.

**Comment by mstarke** [comment]
The references aren't evaluated at view but if you copy the data. If you use "show deferred data" on Keepass you should see the data evaluated combined with the reference string. MacPass does not automatically evaluate references at display. Copy/Paste however works. Although there's a bug in 0.5.1 that prevents the lookup to work on all fields. This is fixed in master where you should be able to copy any item. I should add an option to evaluate the contents on view as well.

**Comment by mstarke** [comment]
Should work in master now.
