### ISSUE TITLE
Database Settings lost across restarts? 

### ISSUE THREAD

**Issue by packplusplus** [mstarke/MacPass#385]
I'm the only one that using this keeppass file. It lives on google drive. Every once and a while I check "database settings" and find a bunch of the fields "unprotected". I can't seem to track down a single root cause, sometimes after restarting the app, sometimes after sleep / unsleep. 

I'm not sure if it's a bug in the display, or whats actually in the file. Next time it happens I'll try a few things. I'd love an application level setting that updated every database I opened to protect all fields, but that may require me doing a pr.

**Comment by mstarke** [comment]
The protection settings are actually useless. Keepass had those for a while but the UI was removed and Keepass restores them to it's own version every time you load a database.

This means if you use MacPass as tick all the boxes and let Keepass save the database again, you'll find that only the password is ticket.

**Comment by packplusplus** [comment]
Can I get a bit more clarification? You say useless, does that mean
all fields are encrypted regardless? or should i only use macpass if
im worried about the text fields?

**Comment by mstarke** [comment]
If you want to get the full details, take a look at the [Keepass Website](http://keepass.info/help/base/security.html).

The stripped down information is: Basically a Keepass2 (.kdbx) Database is just an encrypted XML document with some header information to decrypt the file. This XML data is encrypted as a whole. That means regardless of what you set as protection settings, everything is encrypted. Names, usernames, titles, URLs, notes, tags, binary files, custom icon data even the autotype sequences or the icon ids. The protection settings comes into play on two occasions:

- Keepass on windows uses in memory protection for every field that is marked as protected.
- MacPass stores every protected value XORed with random bytes
- Plain values of protected fields will get XORed with a random stream if the XML document is encrypted. This is the normal use case when saving a .kdbx database.
- Protected fields will however not get XORed when the database is exported as plain XML. Otherwise it would be impossible to import them again, since nothing about the random stream is stored inside the XML document. This information is stored in the header of a .kdbx file.
