### ISSUE TITLE
Target window can't be saved

### ISSUE THREAD

**Issue by sebastianhofer** [mstarke/MacPass#428]
Hi,

I wanted to use the target window feature and it works fine so far, but the configuration can't be saved. Every time I reopen MacPass I have to add the target window again.

Btw. thank you for the grate software. With Ubuntu I used to use keypassx and after my company switched to Mac I searched for a similar software and I found your MacPass.

**Comment by mstarke** [comment]
I cannot reproduce the bug. I just checke with 0.6.2, created 3 target window entries and it worked. Saved, loaded, all 3 were there!

**Comment by mstarke** [comment]
As a side note: KeepassX works very well under OS X, so if you want to just stick to it!

**Comment by sebastianhofer** [comment]
No I don't want to move.

Hm, may be I forget something to do? I click the 'plus' symbol in Window Association and select one window from the drop down. Than I press 'cmd + s'.

**Comment by sebastianhofer** [comment]
Ok I solved the problem. It was the wrong database. I used an old *.kdb database. I generated a keepass2 database, exported my old entries and imported it there. Now I can save my target windows :-)

**Comment by mstarke** [comment]
KDB actually has Autotype features but those are stored in a special format in the notes. I have a stub to parse and save this format but did not implement it.

Some other tidbits:
- MacPass complains in the "save as" dialog when you lose data, but since you just saved this mechanism didn't work. That's an actual bug I need to fix.
- MacPass can save to both formats, that means you can store a KDBX file as KDB (with possible data loss) and vice versa so no need to use external tools to migrate KDB to KDBX.
