### ISSUE TITLE
Are special keys supported for Auto-Type? 

### ISSUE THREAD

**Issue by yantaq** [mstarke/MacPass#474]
This may not be an issue. just wonder if this is supported in 0.6.2.
I would like Auto-Type to fill in the plus sign in this sequence {USERNAME}{TAB}{PASSWORD}{TAB}custom-letter+

I have tried {PLUS} and other variations but couldn't get plus sign (+) appear.
I was wondering if special keys are supported? I am using 0.6.2.

**Comment by mstarke** [comment]
Congratulations, you found a missing feature in the auto type handling. I'll try to add support for Plus and some more in the next binary release. If you want to know, how to those characters, take a look at the [Autotype Help Section](http://keepass.info/help/base/autotype.html#autoseq). Currently this is fixed in the master branch

**Comment by yantaq** [comment]
This is great. Thanks so much for doing such a great work.
