### ISSUE TITLE
Require Keychange every '0' forcing keychange constantly

### ISSUE THREAD

**Issue by cwre** [mstarke/MacPass#476]
I would assume the default of '0' would not require a keychange every time I open my database. Can this be made more obvious?

Another issue: seems like when prompting me to change password I can just cancel and go into database settings to remove the password change prompt.

**Comment by mstarke** [comment]
You're right, it not obvious. There should be a "every time" (0) and "never" (-1) option instead of the actual values.

The second issue is something of a chicken-egg problem. You can enable the enforcement rule but you should also be able to disable it. Otherwise you never would be able to escape the constant password changes. It's considered a nagging reminder but nothing that is set in stone.

**Comment by mstarke** [comment]
And the default is not 0 but -1. A very early version of MacPass used 0 as default and never checked for the values. Around version 0.4 the check was introduces and a lot of old databases had the default 0 value and thus users ran into this issue. The default is -1 (like KeePass) to prevent this from happening.

**Comment by mstarke** [comment]
Current continuous has a better localized interface and makes the settings more clear. The force dialog now also is missing the cancel button.
