### ISSUE TITLE
Auto-Save?

### ISSUE THREAD

**Issue by m-o-e** [mstarke/MacPass#488]
MacPass just lost a bunch of my passwords because I.... shutdown my mac.

**Comment by mstarke** [comment]
The autosave behaviour for OS X doesn't stick so well with the design of a Keepass database, as you have to understand the risks involved. And since MacPass does not support the history correctly this even might cause more trouble. What's include is a save on lock feature, that is, MacPass always stores the database if it gets locked. Since I did change a bit of the undo/redo support some changes aren't register as changes and you will not get a "save changes?" on quit dialog but this should be back in the next release. And sorry for causing you trouble with this behaviour!

**Comment by m-o-e** [comment]
`MacPass always stores the database if it gets locked.`

The lock mode is useless to me, I never lock MacPass.
I never even _look_ at MacPass. I just keep it open in the
background and add passwords to it with the Chrome extension.

Consequently all my changes must be persisted immediately 
or near immediately. I can not switch to MacPass and manually
hit save every time I add a password. That's not how software
works in 2016.

I don't care what MacPass has to do to realize this requirement.
My computer is fast. Rename the old db and save to a new file if
that's what it takes. 

Here is how I currently implement "auto-save on system sleep",
via keyboard maestro automation:

![qcksbn7zgy](https://cloud.githubusercontent.com/assets/1622080/17666286/debe92a8-62ff-11e6-8db4-128613d3456e.png)

Please fix this in MacPass.

**Comment by mstarke** [comment]
If you'd like to implement the feature feel free to open a pull request. If it works I'll gladly merge it.

What I tried to tell you is this. There are more than two users of MacPass and a handful of Keepass users around. I have no plan to diverge MacPass away and add custom behaviour or custom extension to the format as long as it's not needed. The whole purpose of MacPass is feature parity with Keepass, not another password manager as there are plenty of those around.

What you might have missed - and I did not state - MacPass saves on lock and there's a setting to lock the database when the computer goes to sleep. So your custom solution works but is (for this case) not needed. As for saving every time you edit something that's a case for a trigger system. Keepass supports this, and I might implement something like this (or add AppleScript support) but since I even haven't gotten other basic stuff worked out there's simply no time for this. If someone else (or as stated above you) want's to jump in, that's highly apreciated.

And as a kind remark: No one get's a dime putting time into MacPass. We're all here for the fun, not for the hassle ;)

**Comment by mstarke** [comment]
BTW https://keeweb.info has a auto-save feature as far as I'm aware. You might want to give this client a try since it might suit your style more than MacPass.

**Comment by l3ender** [comment]
@mstarke Thanks for all your hard work and positive attitude, despite those who have no gratitude for it

**Comment by m-o-e** [comment]
@mstarke Re lock-after-sleep. I'm aware of that setting.
It would require me to re-enter the (long) db password
after every sleep/wake cycle for no gain. That's why
I had to resort to KM automation.

I'm not belittling the work that went into MacPass,
it's much appreciated. My tone results from the
frustration over the fact that a trivial feature
would prevent predictable loss of user data
and broken expectations here.

It was one of those precious moments where you
sit in front of your screen and think "This didn't really just happen?".

As seen on the issue tracker I'm not the first
to run into this, and surely not the last.

Why not have an auto-save timer in the preferences
that fires a `save if modified` every n seconds while the
window is out of focus (as to not annoy an active user
with intermittent beachballs)?

I tried to emulate that with KM, but due to OSX constraints it
has to bring the window to the foreground to trigger a menu item...

**Comment by mstarke** [comment]
I did suspect you were frustrated about data loss and thus pissed, hence I wasn't trying to keep the heat up. To get you into my head a little more:

I'm not against those little features - on the contrary, but sometime I try to hold them back to implement a proper solution. There are so many little request that often seem trivial and sound vey useful. The proper solution would be the trigger system for many of "Those Little Things". The trivial one is a save-timer or a "save after every modification" setting and considering it's sensible data that might get lost, this is probably the better solution.

To be honest, I never really thought about the use-case of never locking and always sleeping thus having MacPass run unlocked indefinitely.

**Comment by m-o-e** [comment]
Yup, my previous post also came out more harsh than intended,
I apologize for that.

However, I still think the better should not be the
enemy of the good when critical user data is at stake. 
Having triggers would be _nice_, but it should not
stand in the way of preventing loss of passwords.

Running MacPass unlocked indefinitely may seem like an unusual
mode, but it really is the only one that makes sense in conjunction
with the browser extension (which will otherwise just quietly fail
when the database is locked).

The number of people using MacPass in this mode will probably only
go up, as the faith in closed source password managers declines
with every exploit[1].

[1] https://labs.detectify.com/2016/07/27/how-i-made-lastpass-give-me-all-your-passwords/

**Comment by mstarke** [comment]
To prevent this in the future I did experiment with NSDocuments autosaving in place and it seems so work as expected. This might mitigate any need for another custom routine of autosaving and gets the benefit of a version browser.

**Comment by mstarke** [comment]
I have made more progress on autosave of the document. I suspect a lot of edge cases might exist, but for now I think I have found a good solution to work out a lot of lost data issues with this. It's not 100% safe, since some text edits might still be lost, but it's a lot closer to the goal than before. If you like to test it, feel free to use the master branch but there might be stuff broken since I also threw out 10.8 support to get some of the old nssheet api out of the way.

**Comment by saulodigital** [comment]
**@mstarke** just an aside note, all my issues are exactly the same of **m-o-e**.

I was using KeePassX for some years and then discovered MacPass so start using it... Then I had a crash (actually some of them due to a hardware problem) and lost +48 hours of changes including new entries.

I was so angry that stop using MacPass until you implemented this feature.

So, thanks **m-o-e** for insisting (I registered this account to do that but you saved me time) and thanks **mstarke** consider it again.

Best regards.

**Comment by mstarke** [comment]
@saulodigital sorry for having causes do much trouble and creating a tool that stores such sensible data puts the developer in a tight spot sometimes. I tend to be over-cautios in some areas but still bugs creep in that might make a lot of trouble. As stated in the comment above, the master has auto-save in place so this is working if you compile MacPass yourself. I currently am implementing KDBX4 support for KeePassKit to make MacPass compatible with the new format and if not earlier at least then a new release of MacPass will be supplied.

**Comment by saulodigital** [comment]
@mstarke No worries! I like everything in MacPass even the fantastic name. Sure needs some honed edges but it looks great already. I didn't give up, I just stop using it (it's still installed) until this was implemented because I was preparing to talk you into add it. But m-o-e did it already.

However, I wanted to express my case so you could understand another point of view about the need of such feature. I also noticed in your previous comment that the master has auto-save but I never used GitHub so didn't had the time to look into the documentation how it works. I'm Graphic and Multimedia Designer and if I know about coding I would be very glad to join your cause and help, but that is not the case unless you want graphic or multimedia help.

I also think you should do two more things, a dedicated website/domain and a donation button. ; )

**Comment by mstarke** [comment]
2e1e4ad5acd2364825c19c38c81e56af58e9bbe3 has fixes for a lot of "unsaved changes are lost" on save/quit and in combination with auto save enabled I'll consider this as done. If there are issue with the current implementation, please create separate issues for those.
