### ISSUE TITLE
Merge tabs General and Custom to Entry

### ISSUE THREAD

**Issue by tehabe** [mstarke/MacPass#585]
The separation of general and custom makes using the application not very intuitive. So instead of the tabs "General" and "Custom" there should be just one tab "Entry".

**Comment by mstarke** [comment]
One nitpicking about the wording. All the tabs are entry tabs, since every aspect is a property of the entry, hence naming one entry and the rest differently is a bit confusion. Attributes might be a good way for both or fields. There's a UI problem with merging them. The Custom-Fields use a table view to easily support bindings to display all of the custom fields a user has added. Additionally this way it's easy to separate between custom attributes and default attributes. If the table is moved to the first tab, this tab now has two nested scrolling areas which is rather ugly. Using an NSStackView is not easily done since it requires custom controller code for bindings which I rather not add. My only real solution right now is to use a custom NSTableView that doesn't use an NSScrollView so the table is always displaying all it's content.

**Comment by tehabe** [comment]
Leave out the wording. Was just a suggestion. The issue I'm having is, that when I store WiFi passwords I can either create a custom field for SSID or use the username field. In Keepass2Android this isn't an issue because custom field are displayed combined with username and password.

**Comment by mstarke** [comment]
Valid point. I did run some experiments with scroll-less table views and they work - sort of - iff I get the kinks ironed out I surely will merge custom and default attributes into a single view.

**Comment by mstarke** [comment]
General and Custom tabs are merged with ae36b9fb3247ad520c4b7c970e997fa520565af7
