### ISSUE TITLE
Database is broken with Argon2 and Attachments

### ISSUE THREAD

**Issue by ilgio** [mstarke/MacPass#594]
the algoritm argon2 don't work.
when setup this algoritm, the file from 900k , now is 250k
but the db is not accessible
help
![schermata 2017-06-09 alle 11 34 29](https://user-images.githubusercontent.com/26309528/26970443-bc5af324-4d09-11e7-99fd-8b2f85bbf41a.png)

**Comment by mstarke** [comment]
I cannot reproduce this error. Setting Argon2 in the Database and savin/loading works flawlessly. Can you supply more detailed steps to reproduce this error.

**Comment by ilgio** [comment]
I open my DB (algoritm AES - 917KB)
![schermata 2017-06-09 alle 17 29 22](https://user-images.githubusercontent.com/26309528/26982697-7c252c0e-4d39-11e7-9732-4fd708381325.png)

database settings>security>change to argon2>OK
![schermata 2017-06-09 alle 17 31 06](https://user-images.githubusercontent.com/26309528/26982705-7ff76d92-4d39-11e7-894e-9f030af8ad21.png)

File>Save
Close

my file DB now is 256KB
![schermata 2017-06-09 alle 17 32 16](https://user-images.githubusercontent.com/26309528/26982744-a452725e-4d39-11e7-879a-3d94663a9607.png)

Now I open DB, type the correct password and dont entry
![schermata 2017-06-09 alle 17 33 22](https://user-images.githubusercontent.com/26309528/26982793-d267d4cc-4d39-11e7-8bd2-11b9af59be18.png)

**Comment by mstarke** [comment]
That's the same way I converted in my test. Some things that might cause this:
Do you have attachments in your database?
Do you have any custom data in you database (e.g form a keepass plugin)?

I have to take a close look into what could cause this. The error says the XML document cannot be allocated, meaning this should not be a decryption error since the file has been encrypted correctly. It might be cause by a wrong parsed inner header coming form attachments. The reduction in file size also suggest you use attachments since the KDBX4 stores them more efficiently

**Comment by mstarke** [comment]
That's it. Attachment parsing is broken. Thanks for the bug report!

**Comment by ilgio** [comment]
Yes, I have attachments in my database.
the file jpg and png

**Comment by ilgio** [comment]
when do you create a new release?

**Comment by mstarke** [comment]
The continuous snapshot includes the fix.

**Comment by ilgio** [comment]
but it is released 6 day ago
![schermata 2017-06-13 alle 09 54 23](https://user-images.githubusercontent.com/26309528/27071760-6f2c80a0-501e-11e7-9073-8acd5621685a.png)

**Comment by mstarke** [comment]
I have no idea how github determines the dates. Travis builds the tag every time I update it. If you download the file and take a look at the About box you see the build date of the app. Since the app is build only on travis after a push it is the most recent version if the build went through.

<img width="396" alt="screen shot 2017-06-13 at 10 50 07" src="https://user-images.githubusercontent.com/58428/27074089-4ebf4070-5026-11e7-88f1-2fcff641ef19.png">

**Comment by ilgio** [comment]
perfect
it work 
fine thx
