### ISSUE TITLE
Could you return Mavericks (10.9.5) compatibility?

### ISSUE THREAD

**Issue by github22github** [mstarke/MacPass#613]
Please!

**Comment by mstarke** [comment]
Can you tell me, why you stick with 10.9? 10.10 runs on all system supporting 10.9 so it should be possible to upgrade. Since there are a lot of good API changes in 10.10 that make development a lot easier I did drop 10.9 support. My internal rule was to try to support the last 3 OS releases if possible. This is currently the case with 10.10, 10.11 and 10.12. When 10.13 comes around I will even consider dropping 10.10 support.

**Comment by caesar** [comment]
@mstarke I agree with your logic about not supporting when an update is available for all machines running a certain version. BUT, please don't drop support for 10.10 yet, since for it that is not the case – it is the last update available for older-generation Macs. (Myself, I only migrated last-week from a machine for which 10.10 was the end of the line.)

**Comment by mstarke** [comment]
I'm going to stick with 10.10 as minimum for now and close the issue.
