### ISSUE TITLE
MacPass modifies the database every time

### ISSUE THREAD

**Issue by tpluscode** [mstarke/MacPass#649]
I'm sharing the kdbx between machines over ownCloud. Manually, without any integration.

Every since I use MacPass I see that the database is updated every time I open it, I think and it gets synchronised over and over.

With KeePass 2.0 which I used on multiple Windows machines, it would only ever update when I save. And presumably only when stuff actually changes, but I'm not sure about that.

**Comment by mstarke** [comment]
To clarify, what version are you running (you can see it in the about dialog)?

If you're running a continuous build it is a side effect of macOS' autosave. Every time you modify the database, the system saves a version even without you explicitly telling MacPass to do so. This way no data should be lost even if MacPass or worse your mac might crash or get switched of without proposer shutdown. Since every time the database is saved a new random seed is used for the key the encrypted data will change as well. Hence every save (even without changing anything inside the database) will generate a different binary file. Keepass for windows to my knowledge only saves on lock and when you press save. However there should be no problem since the file is always valid and can even be synchronized when changes where made on multiple sides.

**Comment by tpluscode** [comment]
Thanks for the explanation. I'm using Version 0.6.2 (12420)

**Comment by mstarke** [comment]
I'll close this then.
