### ISSUE TITLE
MacPassHttp plugin loaded but not listening

### ISSUE THREAD

**Issue by rofr** [mstarke/MacPass#652]
I have a fresh install of macpass Version 0.7 (20170923100919-continuous)

I see the plugin on the plugins tab but can't connect from chromeipass, to troubleshoot I tried `curl localhost:14455` but get a connection refused. In system.log I found this which might be related:

Sep 24 07:03:42 Roberts-MBP MacPass[2768]: BUG in libdispatch client: kevent[EVFILT_MACHPORT] monitored resource vanished before the source cancel handler was invoked

**Comment by mstarke** [comment]
For MacPassHTTP bugs pleas use the corresponding repository (see https://github.com/MacPass/MacPassHTTP).

Regarding your error, this is due to the binary release of MacPassHTTP being only compatible with the binary release for MacPass 0.6.2. There is no version checking incorporated in plugins so most of the time will fail silently which is the case in your situation. See other bugs related to this. To fix this you can build a version of MacPassHTTP with the current master, as this should run without any issues. When MacPass 0.7 will get releases I will update the plugin to fix any issues as well but currently compatibility is not a focus.

**Comment by mstarke** [comment]
Using both continuous binaries should work!
