### ISSUE TITLE
History issues

### ISSUE THREAD

**Issue by tflo** [mstarke/MacPass#657]
I have two issues with the entry history:

#### GUI glitch

After exiting the history of an entry _all_ entries (from all folders) disappear. Locking/unlocking the file doesn't help. Only closing/reopening the window brings them back.

#### Changes not always recorded

Many changes (for example to the password) are not recorded to the history. But ATM I don't see a pattern when a change gets recorded and when not.

MacPass 0.7 (20171007071014-continuous); macOS 10.13

– Tom

**Comment by mstarke** [comment]
I'll take a look into the GUI glitch, this might be due to some changes to how the entry display is bound in a recent push, I did change that so this might have slipped or it only occurs on 10.13 which I have yet to upgrade to.

About how changes are recorded: I pondered how to solve this a long time and came up with the current method. If you select an entry and start changing anything, the last state will get pushed to history but nothing more until you change to another entry/group and get to that entry again.
My goal was to remove an edit button and just make this as seamless as possible. The other solution would be to push every change to history but this will result in a ton of history entries and with the default settings for Keepass containers (10 history entries), you do not get that much use out of the feature. Other clients like 1Password use special consideration for password fields and store every change on them and just do not record any changes on other fields. Keepass(XC) as well as KyPass uses a modal edit in which you change all attributes you want and when you're done, the entries previous state is pushed to history. This way you will get all changes to any filed you actually committed but not every change that happened while having the modal edit open (e.g. multiple uses of the password generator)

There might be a better solution but I have a strong desire to make the edit as seamless as possible and get the history recording at best fully transparent.

Can you point me to some things you feel are missing in the current solution? Do you want to know and have stored all the passwords you ever created? Might a change in the behaviour to work the same way as before but make every change to a password field record additional history entries solve this for you?

**Comment by tflo** [comment]
> the last state will get pushed to history but nothing more until you change to another entry/group and get to that entry again

Ah, OK, got it now. I _knew_ I was missing something ;)  

> Other clients like 1Password use special consideration for password fields and store every change on them _and just do not record any changes on other fields._

This is not good at all. Often I have important stuff in the Notes field, sometimes as important as the password itself. (For example the phone PIN and card PIN associated with a the bank account of a banking login entry.)

> the default settings for Keepass containers (10 history entries)

In KeePassXC I can set the max. history items/size. If I open a database with an entry with >10 history entries in MacPass the "overflowing" entries are preserved. However I can't set the max. items/size in MacPass; the setting is there (in DB Settings), but I can't enter any values though it is not dimmed.

As an aside: In the same settings sheet, two lines below, it says "Empty Recycle Bin on Quit". The option is dimmed _and checked_, but the Trash is not emptied on quit. (Which is a good thing, of course; but the selected checkbox is a bit misleading.)

> Can you point me to some things you feel are missing in the current solution? Do you want to know and have stored all the passwords you ever created? Might a change in the behaviour to work the same way as before but make every change to a password field record additional history entries solve this for you?

I think your solution of pushing to history only once per entry-editing session is fine. I was just confused as I didn't see the history increase when I hit ⌘S.

A customizable max. history would be useful though.

– Tom

**Comment by mstarke** [comment]
Todays continuous release will include the fix for the history display.

**Comment by mstarke** [comment]
I also enabled the history control to set size and number of entries. This will get pushed soon to continuous.

**Comment by mstarke** [comment]
Todays continuous release included the updated history settings.

**Comment by tflo** [comment]
Looks fine now! Also the fixed recycle bin thingy.

Thank you so much for your work!

– Tom
