### ISSUE TITLE
Global autotype should be case indiferent

### ISSUE THREAD

**Issue by gagarine** [mstarke/MacPass#699]
I don't think auto-type should match case.

**Comment by mstarke** [comment]
Can you be a bit lot precise?

**Comment by gagarine** [comment]
If my browser (tested on Firefox) page title is "Facebook" on my browser but the title of my entry is "facebook" on macpass the global auto-type don't find a match.

**Comment by mstarke** [comment]
This is strange since all the searches are case insensitive.

To test this I used the following html document:

```html
<!DOCTYPE html>
<html>
<head>
	<title>title</title>
</head>
<body>
<form>
	<input type="text" name="username">
	<input type="password" name="password">
	<input type="submit" name="submit">
</form>
</body>
</html>
```

I created a database with three entries
<img width="410" alt="screen shot 2017-11-25 at 22 25 22" src="https://user-images.githubusercontent.com/58428/33234966-911b900a-d22f-11e7-872b-508c548e8224.png">

Invoking global autotype with firefox brought up all three hits in the selection dialog:
<img width="592" alt="screen shot 2017-11-25 at 22 27 31" src="https://user-images.githubusercontent.com/58428/33234981-e30cd23e-d22f-11e7-953f-83c71b06104e.png">

**Comment by mstarke** [comment]
Can you confirm the behaviour? If not I need look into it.

**Comment by gagarine** [comment]
Nop you right. I tried it again and it works. Sorry.

Don't know really why, but sometimes it doesn't... Perhaps is because of the use of CTRL in the shortcut that is capted by the website. I will open a new bug when I'm more confident of what's going on.
