### ISSUE TITLE
Can't accept or deny access from Chrome Extension KeepassHelper

### ISSUE THREAD

**Issue by jeffderbyshire** [mstarke/MacPass#704]
![screen shot 2017-12-01 at 11 02 06 am](https://user-images.githubusercontent.com/5561193/33494022-8a43ddda-d687-11e7-8ee2-da22ff9bdb67.png)

When trying to request access from keepasshelper extenions in chrome, this dialog comes up, but I can't select either Allow or Deny.  I must force quit MacPass to continue using it.
MacPass version Version 0.7.3 (17830)
MacPassHTTP 0.2.1(39)
Chrome Version 62.0.3202.94 (Official Build) (64-bit)
KeePassHelper Password Manager 0.3.1
OSX Version 10.11.6

Not sure if this is MacPass problem, but I wanted to post here in case others are experiencing this problem.

Thanks.

**Comment by mstarke** [comment]
Hi Jeff. Did you read the release notes of MacPass? If so, how should I phrase the warning about plugins breaking differently so that you wouldn't have missed it?

To fix your problem please install MacPassHTTP 0.3.x.

Sorry for the rant but this keeps coming up all the time and I have no clue why so many users miss the bold warning.

**Comment by jeffderbyshire** [comment]
Ah Ha, thank you for informing me to RTFM :).  Is there any way to disable plugins, maybe give popup warning saying it won't work with new MacPass version?  Thanks.

**Comment by mstarke** [comment]
See the discussion in #703. I guess since this seems to come up as a regular source of problems I should actually spent some time on making this better. A global "disable plugins" settings is another good solutions. I enhanced the plugin loading a lot recently so you get more out of it and are able to install/uninstall via the settings but no system for compatibility checking is in place.
