### ISSUE TITLE
Download Icon creates blank icon for some sites

### ISSUE THREAD

**Issue by erjiang** [mstarke/MacPass#709]
I assume that the Download Icon feature uses the URL field for an account to figure out where to look for an icon.

Steps to reproduce:

1. Create New Entry
2. Put in "https://appleid.apple.com/#!&page=signin" as the URL.
3. Click on the icon in MacPass
4. Select Download Icon.

See that a blank icon is added to the icon collection (can be hard to see).

This problem also occurs for "https://dashboard.heroku.com/"

**Comment by mstarke** [comment]
The system is rather simple. It tries to download a favicon.ico file and uses that. If no icon is found (a non 200 response code) and data was received the icon is created. This sometimes leads to the described behavior of empty images. A simple enhancement should be to test if the image actually is an image since this is currently silently ignored without failure. 

A more sophisticated approach would be to try more icon files, parse the header for images or use the google favicon service but I did not spent that much time on the feature. 

Fixing the empty image behavior is vital and easy and should be added, the rest requires a lot more work. If you want to takle this, I'd be very happy about a pull request!

**Comment by mstarke** [comment]
You do know that you can drag an image into the icon to set it as a custom icon?

**Comment by erjiang** [comment]
I renamed the issue since obviously I don't expect it to "work" for all sites, but it was the addition of a blank icon that really threw me off.

I also didn't realize that dragging an image file onto the icon was the UI for using a custom file. I would have expected a "Open file..." button next to "Use Default Icon". But honestly, if Download Icon didn't work, I just give up at that step and leave the icon as the default icon.

**Comment by erjiang** [comment]
It looks like where you try creating the KPKIcon using with initWithImageData already checks if the object is nil, so I'm thinking something like the following would work:

```
diff --git a/KeePassKit/Core/KPKIcon.m b/KeePassKit/Core/KPKIcon.m
index 88cc8fd..04508cc 100644
--- a/KeePassKit/Core/KPKIcon.m
+++ b/KeePassKit/Core/KPKIcon.m
@@ -64,6 +64,11 @@
       _uuid = uuid;
     }
   }
+  // if NSUIImage fails to understand data, then this KPKIcon should be nil as well
+  if (!_image) {
+    [self release];
+    return nil;
+  }
   return self;
 }
```
 
I don't know objc nor do I know how to compile all this, so I think it's best that someone else makes the PR.

**Comment by mstarke** [comment]
Thanks for the feedback. I went the other way and checked on the KPKIcon since I'm not sure a KPKIcon should get niled if it does not have an image. Regarding you code: The release message is not necessary since the code is compiled with ARC so this will actually result in a compiler error.

**Comment by mstarke** [comment]
The discoverability is not ideal but I hesitated to clutter the dialog with even more button. It might be useful to reserve a special place like "Drop custom icons here" or something like this to make it more obvious. As a long time macOS user, I'm more prone to trying drag and drop since it feels natural to me even on places that do not seem to support it at first glance.
