### ISSUE TITLE
Port of the synchronisation feature

### ISSUE THREAD

**Issue by alexanderadam** [mstarke/MacPass#83]
I think it is essential for some people who wants to use it together:

http://keepass.info/help/v2/sync.html

Thank you very much

**Comment by petep** [comment]
+1 . This feature is also becoming a showstopper for me in an otherwise excellent product.

**Comment by h-svab** [comment]
+1

**Comment by tecgen** [comment]
+1 :)

**Comment by ricard33** [comment]
:+1:

**Comment by oscarfroberg** [comment]
I'll throw $20 in there for syncing. :+1:

**Comment by bhawker** [comment]
+1, this would be a killer feature.

**Comment by csjones** [comment]
:+1:

**Comment by holle** [comment]
+1

**Comment by costerwi** [comment]
+1, this would simplify my life

**Comment by lgraf** [comment]
+1

**Comment by realdubb** [comment]
👍

**Comment by mstarke** [comment]
See https://github.com/MacPass/MacPassHTTP/issues/8

**Comment by woyczek** [comment]
The Keepass XML model includes a timestamp for last modification.
It may be lossy, but may be used to compare two entries from two files.

I did such a thing, to re-synchronize databases, with simple shell and XML export/import.

It may be used with warnings, but could be adapted to the live keepass data model.

**Comment by mstarke** [comment]
This features should be implemented the same way Keepass does it, that is, it uses modification, access, moved dates and deleted objects. The XML format is simply the inner unencrypted XML file KDBX files consist of. The upcoming KDBX4 format will have some modifications to this but the XML format for import/export still holds all information available. The feature should work on the internal structure to get the best user experience and it's very helpful to ease the "reload after external changes" workflow. An external XML base process should actual doe exactly the same but has the disadvantage of being external.

**Comment by srameko** [comment]
+1, because if you want to sync two KDBX there is no support. XML import just replace current database. Thx.

**Comment by WebWeave** [comment]
+1
It's really a miss dat MacPas doens't have this.

**Comment by mariusmuntean** [comment]
I'm also missing this feature. Just recently I ran the portable Windows version of KeePass with Mono to sync multiple databases. It wasn't nice.

**Comment by ElizarovEugene** [comment]
Sorry for #636
The same I think this functionality is very necessary

**Comment by mstarke** [comment]
Current continuous release has sync on file change as well via a Merge action.

**Comment by mariusmuntean** [comment]
@mstarke I'm really happy for this change.
Can we also have a view with the differences? Even if merging succeeded. Otherwise I don't know if I want the changes or not.

Keep up the good work.

**Comment by mstarke** [comment]
The differences view is AFAIK not present in any KeePass application since the merge algorithm is designed to preserve data. Furthermore the rationale behind this is, that most of the time you are the one introducing changes by merging two a databases you use. That said, I get your desire to see differences. It's easily possible to add the view but adding an option to reject the changes is a tag more complicated. Also, consider the extreme where your database is shared and edited by many users constantly. You then would get a "Merge review" screen a lot and I would wager that this completely defeats the purpose. What might be a viable alternative is a transcript of database actions. This way you can review the data level changes in a compact linear form but lack the possibility to interact with the merge process.

**Comment by mstarke** [comment]
0.7 officially introduces merging so this feature is implemented. What should be considered is a "dry merge" approach to view and even reject changes.

**Comment by mstarke** [comment]
Separate issue for merge-view #701
